#! python

import cli

if( __name__ == "__main__" ):
    print("Exploring Wikipedia to reach Philosophy page...")
    print("Starting from a random Wikipedia article...\n")
    cli.scrape("/wiki/Special:Random")